{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a spec for availabilityCXS v1 REST API",
    "version" : "v3",
    "title" : "Swagger spec for availabilityCXS v1 REST API"
  },
  "host" : "www.dummyhost.com",
  "basePath" : "/availabilityCXS/v1",
  "schemes" : [ "https" ],
  "paths" : {
    "/packagetypes" : {
      "get" : {
        "summary" : "",
        "description" : "",
        "operationId" : "getPackageTypes",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/GetPackageTypesOutputVO"
            }
          }
        }
      }
    },
    "/specialservices/homedeliveryoptions" : {
      "get" : {
        "summary" : "",
        "description" : "",
        "operationId" : "getHomeDeliveryOptions",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "shipDate",
          "in" : "query",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "senderpostalcode",
          "in" : "query",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "sendercountrycode",
          "in" : "query",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "recipientpostalcode",
          "in" : "query",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "recipientcountrycode",
          "in" : "query",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/HomeDeliveryOptionsOutputVO"
            }
          }
        }
      }
    },
    "/specialservices/returnshippingtypes" : {
      "post" : {
        "summary" : "",
        "description" : "",
        "operationId" : "shippingLabelType",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/ReturnShippingTypesInputVO"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/ReturnShippingTypesOutputVO"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "AccountNumber" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "string"
        },
        "key" : {
          "type" : "string"
        }
      },
      "example" : {
        "value" : "value",
        "key" : "key"
      }
    },
    "Address" : {
      "type" : "object",
      "properties" : {
        "streetLines" : {
          "type" : "array",
          "xml" : {
            "name" : "streetLine",
            "wrapped" : true
          },
          "items" : {
            "type" : "string"
          }
        },
        "city" : {
          "type" : "string"
        },
        "stateOrProvinceCode" : {
          "type" : "string"
        },
        "postalCode" : {
          "type" : "string"
        },
        "countryCode" : {
          "type" : "string"
        },
        "residential" : {
          "type" : "boolean",
          "default" : false
        },
        "addressVerificationId" : {
          "type" : "string"
        },
        "addressClassification" : {
          "type" : "string",
          "enum" : [ "MIXED", "UNKNOWN", "BUSINESS", "RESIDENTIAL" ]
        },
        "addressClassificationConfidence" : {
          "type" : "string",
          "enum" : [ "POTENTIAL", "PERMANENT" ]
        },
        "shareId" : {
          "type" : "string"
        }
      },
      "example" : {
        "residential" : false,
        "addressClassification" : "MIXED",
        "city" : "city",
        "countryCode" : "countryCode",
        "streetLines" : [ "streetLines", "streetLines" ],
        "postalCode" : "postalCode",
        "addressVerificationId" : "addressVerificationId",
        "addressClassificationConfidence" : "POTENTIAL",
        "stateOrProvinceCode" : "stateOrProvinceCode",
        "shareId" : "shareId"
      }
    },
    "AlcoholDetail" : {
      "type" : "object",
      "properties" : {
        "alcoholRecipientType" : {
          "type" : "string",
          "enum" : [ "LICENSEE", "CONSUMER" ]
        },
        "shipperAgreementType" : {
          "type" : "string"
        }
      },
      "example" : {
        "alcoholRecipientType" : "LICENSEE",
        "shipperAgreementType" : "shipperAgreementType"
      }
    },
    "BatteryDetail" : {
      "type" : "object",
      "properties" : {
        "batteryMaterialType" : {
          "type" : "string",
          "enum" : [ "LITHIUM_METAL", "LITHIUM_ION" ]
        },
        "batteryPackingType" : {
          "type" : "string",
          "enum" : [ "CONTAINED_IN_EQUIPMENT", "PACKED_WITH_EQUIPMENT" ]
        },
        "batteryRegulatoryType" : {
          "type" : "string",
          "enum" : [ "IATA_SECTION_II" ]
        }
      },
      "example" : {
        "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
        "batteryRegulatoryType" : "IATA_SECTION_II",
        "batteryMaterialType" : "LITHIUM_METAL"
      }
    },
    "CODDetail" : {
      "type" : "object",
      "properties" : {
        "codCollectionAmount" : {
          "$ref" : "#/definitions/Money"
        },
        "codCollectionType" : {
          "type" : "string",
          "enum" : [ "ANY", "CASH", "COMPANY_CHECK", "GUARANTEED_FUNDS", "PERSONAL_CHECK" ]
        }
      },
      "example" : {
        "codCollectionType" : "ANY",
        "codCollectionAmount" : {
          "amount" : 3.616076749251911,
          "currencySymbol" : "currencySymbol",
          "currency" : "currency"
        }
      }
    },
    "CXSAlert" : {
      "type" : "object",
      "properties" : {
        "code" : {
          "type" : "string"
        },
        "message" : {
          "type" : "string"
        },
        "alertType" : {
          "type" : "string",
          "enum" : [ "NOTE", "WARNING" ]
        }
      },
      "example" : {
        "code" : "code",
        "alertType" : "NOTE",
        "message" : "message"
      }
    },
    "Contact" : {
      "type" : "object",
      "properties" : {
        "personName" : {
          "type" : "string"
        },
        "parsedPersonName" : {
          "$ref" : "#/definitions/ParsedPersonName"
        },
        "companyName" : {
          "type" : "string"
        },
        "phoneNumber" : {
          "type" : "string"
        },
        "phoneExtension" : {
          "type" : "string"
        },
        "emailAddress" : {
          "type" : "string"
        },
        "faxNumber" : {
          "type" : "string"
        },
        "contactId" : {
          "type" : "string"
        },
        "stateTaxId" : {
          "type" : "string"
        },
        "fedralTaxId" : {
          "type" : "string"
        }
      },
      "example" : {
        "personName" : "personName",
        "fedralTaxId" : "fedralTaxId",
        "emailAddress" : "emailAddress",
        "parsedPersonName" : {
          "firstName" : "firstName",
          "lastName" : "lastName",
          "middleName" : "middleName",
          "suffix" : "suffix"
        },
        "phoneNumber" : "phoneNumber",
        "contactId" : "contactId",
        "phoneExtension" : "phoneExtension",
        "companyName" : "companyName",
        "faxNumber" : "faxNumber",
        "stateTaxId" : "stateTaxId"
      }
    },
    "ContentRecord" : {
      "type" : "object",
      "properties" : {
        "partNumber" : {
          "type" : "string"
        },
        "itemNumber" : {
          "type" : "string"
        },
        "receivedQuantity" : {
          "type" : "integer",
          "format" : "int32"
        },
        "description" : {
          "type" : "string"
        }
      },
      "example" : {
        "itemNumber" : "itemNumber",
        "receivedQuantity" : 4,
        "description" : "description",
        "partNumber" : "partNumber"
      }
    },
    "CustomerReference" : {
      "type" : "object",
      "properties" : {
        "customerReferenceType" : {
          "type" : "string",
          "enum" : [ "BILL_OF_LADING", "CUSTOMER_REFERENCE", "DEPARTMENT_NUMBER", "INVOICE_NUMBER", "P_O_NUMBER", "SHIPMENT_INTEGRITY", "INTRACOUNTRY_REGULATORY_REFERENCE", "STORE_NUMBER", "RMA_ASSOCIATION", "SHIPPER_ID1", "SHIPPER_ID2" ]
        },
        "value" : {
          "type" : "string"
        }
      },
      "example" : {
        "customerReferenceType" : "BILL_OF_LADING",
        "value" : "value"
      }
    },
    "DangerousGoodsDetail" : {
      "type" : "object",
      "properties" : {
        "accessibility" : {
          "type" : "string",
          "enum" : [ "ACCESSIBLE", "INACCESSIBLE" ]
        },
        "options" : {
          "type" : "array",
          "xml" : {
            "name" : "optionsList",
            "wrapped" : true
          },
          "items" : {
            "type" : "string",
            "enum" : [ "HAZARDOUS_MATERIALS", "BATTERY", "ORM_D", "REPORTABLE_QUANTITIES", "SMALL_QUANTITY_EXCEPTION" ]
          }
        }
      },
      "example" : {
        "accessibility" : "ACCESSIBLE",
        "options" : [ "HAZARDOUS_MATERIALS", "HAZARDOUS_MATERIALS" ]
      }
    },
    "Dimensions" : {
      "type" : "object",
      "properties" : {
        "length" : {
          "type" : "integer",
          "format" : "int32"
        },
        "width" : {
          "type" : "integer",
          "format" : "int32"
        },
        "height" : {
          "type" : "integer",
          "format" : "int32"
        },
        "units" : {
          "type" : "string",
          "enum" : [ "CM", "IN" ]
        }
      },
      "example" : {
        "length" : 6,
        "width" : 1,
        "units" : "CM",
        "height" : 5
      }
    },
    "GetPackageTypesOutputVO" : {
      "type" : "object",
      "properties" : {
        "packagingTypeList" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "FEDEX_ENVELOPE", "FEDEX_PAK", "FEDEX_BOX", "FEDEX_SMALL_BOX", "FEDEX_MEDIUM_BOX", "FEDEX_LARGE_BOX", "FEDEX_EXTRA_LARGE_BOX", "FEDEX_TUBE", "FEDEX_10KG_BOX", "FEDEX_25KG_BOX", "YOUR_PACKAGING", "SELFPACKAGE_BAG", "SELFPACKAGE_BARREL", "SELFPACKAGE_BASKET", "SELFPACKAGE_BOX", "SELFPACKAGE_BUCKET", "SELFPACKAGE_BUNDLE", "SELFPACKAGE_CAGE", "SELFPACKAGE_CARTON", "SELFPACKAGE_CASE", "SELFPACKAGE_CHEST", "SELFPACKAGE_CONTAINER", "SELFPACKAGE_CRATE", "SELFPACKAGE_CYLINDER", "SELFPACKAGE_DRUM", "SELFPACKAGE_ENVELOPE", "SELFPACKAGE_PACKAGE", "SELFPACKAGE_PAIL", "SELFPACKAGE_PALLET", "SELFPACKAGE_PARCEL", "SELFPACKAGE_PIECES", "SELFPACKAGE_REEL", "SELFPACKAGE_ROLL", "SELFPACKAGE_SACK", "SELFPACKAGE_SHRINKWRAPPED", "SELFPACKAGE_SKID", "SELFPACKAGE_TANK", "SELFPACKAGE_TOTEBIN", "SELFPACKAGE_TUBE", "SELFPACKAGE_UNIT", "SELFPACKAGE_OTHER", "FEDEX_UK_PAK" ]
          }
        },
        "cxsalerts" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CXSAlert"
          }
        }
      },
      "example" : {
        "packagingTypeList" : [ "FEDEX_ENVELOPE", "FEDEX_ENVELOPE" ],
        "cxsalerts" : [ {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        }, {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        } ]
      }
    },
    "HomeDeliveryOptionsOutputVO" : {
      "type" : "object",
      "properties" : {
        "dateCertainDeliveryDates" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "dateCertainHomeDeliveryAllowed" : {
          "type" : "boolean",
          "default" : false
        },
        "appointmentHomeDeliveryAllowed" : {
          "type" : "boolean",
          "default" : false
        },
        "eveningHomeDeliveryAllowed" : {
          "type" : "boolean",
          "default" : false
        },
        "cxsalerts" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CXSAlert"
          }
        }
      },
      "example" : {
        "dateCertainHomeDeliveryAllowed" : false,
        "dateCertainDeliveryDates" : [ "dateCertainDeliveryDates", "dateCertainDeliveryDates" ],
        "eveningHomeDeliveryAllowed" : false,
        "appointmentHomeDeliveryAllowed" : false,
        "cxsalerts" : [ {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        }, {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        } ]
      }
    },
    "Money" : {
      "type" : "object",
      "properties" : {
        "currency" : {
          "type" : "string"
        },
        "amount" : {
          "type" : "number",
          "format" : "double"
        },
        "currencySymbol" : {
          "type" : "string"
        }
      },
      "example" : {
        "amount" : 3.616076749251911,
        "currencySymbol" : "currencySymbol",
        "currency" : "currency"
      }
    },
    "PackageSpecialServicesRequested" : {
      "type" : "object",
      "properties" : {
        "specialServiceTypes" : {
          "type" : "array",
          "xml" : {
            "name" : "specialServiceType",
            "wrapped" : true
          },
          "items" : {
            "type" : "string",
            "enum" : [ "ALCOHOL", "APPOINTMENT_DELIVERY", "COD", "DANGEROUS_GOODS", "DRY_ICE", "NON_STANDARD_CONTAINER", "PIECE_COUNT_VERIFICATION", "PRIORITY_ALERT", "SIGNATURE_OPTION", "BATTERY", "HOME_DELIVERY_EVENING", "HOME_DELIVERY_DATE_CERTAIN", "HOME_DELIVERY_APPOINMENT", "ALCOHOL_LICENSEE", "ALCOHOL_CONSUMER", "NON_STANDARD_PACKAGING", "ORM_D", "BROKER", "INTERNATIONAL_CONTROLLED_EXPORT_SERVICE", "PROTECTION_FROM_FREEZING", "HOLD_AT_LOCATION", "INSIDE_DELIVERY", "INSIDE_PICKUP", "SMALL_QUANTITY", "HAZARDOUS_MATERIALS", "LITHIUM_BATTERIES", "BLOCK_SHIPMENT_DATA", "ITAR", "OVERSIZED", "SHIPMENT_CONTENTS", "BARREL" ]
          }
        },
        "codDetail" : {
          "$ref" : "#/definitions/CODDetail"
        },
        "signatureOptionDetail" : {
          "$ref" : "#/definitions/SignatureOptionDetail"
        },
        "dryIceWeight" : {
          "$ref" : "#/definitions/Weight"
        },
        "dangerousGoodsDetail" : {
          "$ref" : "#/definitions/DangerousGoodsDetail"
        },
        "alcoholDetail" : {
          "$ref" : "#/definitions/AlcoholDetail"
        },
        "pieceCountVerificationBoxCount" : {
          "type" : "integer",
          "format" : "int32"
        },
        "batteryDetails" : {
          "type" : "array",
          "xml" : {
            "name" : "batteryDetail",
            "wrapped" : true
          },
          "items" : {
            "$ref" : "#/definitions/BatteryDetail"
          }
        }
      },
      "example" : {
        "signatureOptionDetail" : {
          "signatureOptionType" : "SERVICE_DEFAULT",
          "signatureReleaseNumber" : "signatureReleaseNumber"
        },
        "alcoholDetail" : {
          "alcoholRecipientType" : "LICENSEE",
          "shipperAgreementType" : "shipperAgreementType"
        },
        "dangerousGoodsDetail" : {
          "accessibility" : "ACCESSIBLE",
          "options" : [ "HAZARDOUS_MATERIALS", "HAZARDOUS_MATERIALS" ]
        },
        "pieceCountVerificationBoxCount" : 2,
        "batteryDetails" : [ {
          "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
          "batteryRegulatoryType" : "IATA_SECTION_II",
          "batteryMaterialType" : "LITHIUM_METAL"
        }, {
          "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
          "batteryRegulatoryType" : "IATA_SECTION_II",
          "batteryMaterialType" : "LITHIUM_METAL"
        } ],
        "specialServiceTypes" : [ "ALCOHOL", "ALCOHOL" ],
        "codDetail" : {
          "codCollectionType" : "ANY",
          "codCollectionAmount" : {
            "amount" : 3.616076749251911,
            "currencySymbol" : "currencySymbol",
            "currency" : "currency"
          }
        },
        "dryIceWeight" : {
          "units" : "KG",
          "value" : 2.3021358869347655
        }
      }
    },
    "ParsedPersonName" : {
      "type" : "object",
      "properties" : {
        "firstName" : {
          "type" : "string"
        },
        "middleName" : {
          "type" : "string"
        },
        "lastName" : {
          "type" : "string"
        },
        "suffix" : {
          "type" : "string"
        }
      },
      "example" : {
        "firstName" : "firstName",
        "lastName" : "lastName",
        "middleName" : "middleName",
        "suffix" : "suffix"
      }
    },
    "Party" : {
      "type" : "object",
      "properties" : {
        "accountNumber" : {
          "$ref" : "#/definitions/AccountNumber"
        },
        "tins" : {
          "type" : "array",
          "xml" : {
            "name" : "tinsList",
            "wrapped" : true
          },
          "items" : {
            "$ref" : "#/definitions/TaxpayerIdentification"
          }
        },
        "contact" : {
          "$ref" : "#/definitions/Contact"
        },
        "address" : {
          "$ref" : "#/definitions/Address"
        },
        "deliveryInstructions" : {
          "type" : "string"
        },
        "piece" : {
          "$ref" : "#/definitions/Piece"
        },
        "referenceInfo" : {
          "$ref" : "#/definitions/ReferenceInfo"
        },
        "productInfo" : {
          "$ref" : "#/definitions/ProductInfo"
        }
      },
      "example" : {
        "address" : {
          "residential" : false,
          "addressClassification" : "MIXED",
          "city" : "city",
          "countryCode" : "countryCode",
          "streetLines" : [ "streetLines", "streetLines" ],
          "postalCode" : "postalCode",
          "addressVerificationId" : "addressVerificationId",
          "addressClassificationConfidence" : "POTENTIAL",
          "stateOrProvinceCode" : "stateOrProvinceCode",
          "shareId" : "shareId"
        },
        "piece" : {
          "declaredValueCurrencyCode" : "declaredValueCurrencyCode",
          "unitsOfMeasure" : {
            "code" : "code",
            "name" : "name",
            "originalCode" : "originalCode",
            "category" : "category",
            "value" : "value"
          },
          "declaredValue" : 0.80082819046101150206595775671303272247314453125,
          "dimensions" : {
            "length" : 6,
            "width" : 1,
            "units" : "CM",
            "height" : 5
          }
        },
        "contact" : {
          "personName" : "personName",
          "fedralTaxId" : "fedralTaxId",
          "emailAddress" : "emailAddress",
          "parsedPersonName" : {
            "firstName" : "firstName",
            "lastName" : "lastName",
            "middleName" : "middleName",
            "suffix" : "suffix"
          },
          "phoneNumber" : "phoneNumber",
          "contactId" : "contactId",
          "phoneExtension" : "phoneExtension",
          "companyName" : "companyName",
          "faxNumber" : "faxNumber",
          "stateTaxId" : "stateTaxId"
        },
        "accountNumber" : {
          "value" : "value",
          "key" : "key"
        },
        "tins" : [ {
          "number" : "number",
          "tinType" : "BUSINESS_NATIONAL",
          "usage" : "usage",
          "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
          "expirationDate" : "2000-01-23T04:56:07.000+00:00"
        }, {
          "number" : "number",
          "tinType" : "BUSINESS_NATIONAL",
          "usage" : "usage",
          "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
          "expirationDate" : "2000-01-23T04:56:07.000+00:00"
        } ],
        "referenceInfo" : {
          "regulatoryReferenceNumber" : "regulatoryReferenceNumber",
          "yourReference" : "yourReference",
          "countryCode" : "countryCode",
          "postalCode" : "postalCode",
          "purchaseOrderNumber" : "purchaseOrderNumber",
          "departmentNumber" : "departmentNumber",
          "invoiceNumber" : "invoiceNumber",
          "accountNbr" : "accountNbr",
          "shipDate" : "shipDate",
          "referenceValue" : "referenceValue"
        },
        "deliveryInstructions" : "deliveryInstructions",
        "productInfo" : {
          "customsValueAndWeightSpecifiedAsUnit" : false,
          "quantity" : 5,
          "customsValue" : 7.061401241503109105224211816675961017608642578125,
          "weightUnitOfMeasureCode" : "weightUnitOfMeasureCode",
          "description" : "description",
          "weight" : {
            "units" : "KG",
            "value" : 2.3021358869347655
          },
          "sedRequired" : false,
          "productType" : "DOCUMENTS",
          "unitOfMeasureCode" : "unitOfMeasureCode",
          "countryOfManufactureCode" : "countryOfManufactureCode"
        }
      }
    },
    "Piece" : {
      "type" : "object",
      "properties" : {
        "declaredValue" : {
          "type" : "number"
        },
        "declaredValueCurrencyCode" : {
          "type" : "string"
        },
        "dimensions" : {
          "$ref" : "#/definitions/Dimensions"
        },
        "unitsOfMeasure" : {
          "$ref" : "#/definitions/UnitsOfMeasure"
        }
      },
      "example" : {
        "declaredValueCurrencyCode" : "declaredValueCurrencyCode",
        "unitsOfMeasure" : {
          "code" : "code",
          "name" : "name",
          "originalCode" : "originalCode",
          "category" : "category",
          "value" : "value"
        },
        "declaredValue" : 0.80082819046101150206595775671303272247314453125,
        "dimensions" : {
          "length" : 6,
          "width" : 1,
          "units" : "CM",
          "height" : 5
        }
      }
    },
    "ProductInfo" : {
      "type" : "object",
      "properties" : {
        "productType" : {
          "type" : "string",
          "enum" : [ "DOCUMENTS", "COMMODITIES" ]
        },
        "description" : {
          "type" : "string"
        },
        "countryOfManufactureCode" : {
          "type" : "string"
        },
        "quantity" : {
          "type" : "integer",
          "format" : "int32"
        },
        "unitOfMeasureCode" : {
          "type" : "string"
        },
        "customsValueAndWeightSpecifiedAsUnit" : {
          "type" : "boolean",
          "default" : false
        },
        "weight" : {
          "$ref" : "#/definitions/Weight"
        },
        "weightUnitOfMeasureCode" : {
          "type" : "string"
        },
        "customsValue" : {
          "type" : "number"
        },
        "sedRequired" : {
          "type" : "boolean",
          "default" : false
        }
      },
      "example" : {
        "customsValueAndWeightSpecifiedAsUnit" : false,
        "quantity" : 5,
        "customsValue" : 7.061401241503109105224211816675961017608642578125,
        "weightUnitOfMeasureCode" : "weightUnitOfMeasureCode",
        "description" : "description",
        "weight" : {
          "units" : "KG",
          "value" : 2.3021358869347655
        },
        "sedRequired" : false,
        "productType" : "DOCUMENTS",
        "unitOfMeasureCode" : "unitOfMeasureCode",
        "countryOfManufactureCode" : "countryOfManufactureCode"
      }
    },
    "ReferenceInfo" : {
      "type" : "object",
      "required" : [ "accountNbr", "countryCode", "postalCode", "referenceValue", "shipDate" ],
      "properties" : {
        "referenceValue" : {
          "type" : "string"
        },
        "accountNbr" : {
          "type" : "string"
        },
        "postalCode" : {
          "type" : "string"
        },
        "countryCode" : {
          "type" : "string"
        },
        "shipDate" : {
          "type" : "string"
        },
        "yourReference" : {
          "type" : "string"
        },
        "purchaseOrderNumber" : {
          "type" : "string"
        },
        "invoiceNumber" : {
          "type" : "string"
        },
        "departmentNumber" : {
          "type" : "string"
        },
        "regulatoryReferenceNumber" : {
          "type" : "string"
        }
      },
      "example" : {
        "regulatoryReferenceNumber" : "regulatoryReferenceNumber",
        "yourReference" : "yourReference",
        "countryCode" : "countryCode",
        "postalCode" : "postalCode",
        "purchaseOrderNumber" : "purchaseOrderNumber",
        "departmentNumber" : "departmentNumber",
        "invoiceNumber" : "invoiceNumber",
        "accountNbr" : "accountNbr",
        "shipDate" : "shipDate",
        "referenceValue" : "referenceValue"
      }
    },
    "RequestedPackageLineItem" : {
      "type" : "object",
      "properties" : {
        "groupPackageCount" : {
          "type" : "integer",
          "format" : "int32"
        },
        "insuredValue" : {
          "$ref" : "#/definitions/Money"
        },
        "weight" : {
          "$ref" : "#/definitions/Weight"
        },
        "dimensions" : {
          "$ref" : "#/definitions/Dimensions"
        },
        "physicalPackaging" : {
          "type" : "string",
          "enum" : [ "FEDEX_ENVELOPE", "FEDEX_PAK", "FEDEX_BOX", "FEDEX_SMALL_BOX", "FEDEX_MEDIUM_BOX", "FEDEX_LARGE_BOX", "FEDEX_EXTRA_LARGE_BOX", "FEDEX_TUBE", "FEDEX_10KG_BOX", "FEDEX_25KG_BOX", "YOUR_PACKAGING", "SELFPACKAGE_BAG", "SELFPACKAGE_BARREL", "SELFPACKAGE_BASKET", "SELFPACKAGE_BOX", "SELFPACKAGE_BUCKET", "SELFPACKAGE_BUNDLE", "SELFPACKAGE_CAGE", "SELFPACKAGE_CARTON", "SELFPACKAGE_CASE", "SELFPACKAGE_CHEST", "SELFPACKAGE_CONTAINER", "SELFPACKAGE_CRATE", "SELFPACKAGE_CYLINDER", "SELFPACKAGE_DRUM", "SELFPACKAGE_ENVELOPE", "SELFPACKAGE_PACKAGE", "SELFPACKAGE_PAIL", "SELFPACKAGE_PALLET", "SELFPACKAGE_PARCEL", "SELFPACKAGE_PIECES", "SELFPACKAGE_REEL", "SELFPACKAGE_ROLL", "SELFPACKAGE_SACK", "SELFPACKAGE_SHRINKWRAPPED", "SELFPACKAGE_SKID", "SELFPACKAGE_TANK", "SELFPACKAGE_TOTEBIN", "SELFPACKAGE_TUBE", "SELFPACKAGE_UNIT", "SELFPACKAGE_OTHER" ]
        },
        "itemDescription" : {
          "type" : "string"
        },
        "itemDescriptionForClearance" : {
          "type" : "string"
        },
        "customerReferences" : {
          "type" : "array",
          "xml" : {
            "name" : "customerReference",
            "wrapped" : true
          },
          "items" : {
            "$ref" : "#/definitions/CustomerReference"
          }
        },
        "packageSpecialServices" : {
          "$ref" : "#/definitions/PackageSpecialServicesRequested"
        },
        "contentRecord" : {
          "$ref" : "#/definitions/ContentRecord"
        }
      },
      "example" : {
        "physicalPackaging" : "FEDEX_ENVELOPE",
        "groupPackageCount" : 9,
        "itemDescriptionForClearance" : "itemDescriptionForClearance",
        "customerReferences" : [ {
          "customerReferenceType" : "BILL_OF_LADING",
          "value" : "value"
        }, {
          "customerReferenceType" : "BILL_OF_LADING",
          "value" : "value"
        } ],
        "contentRecord" : {
          "itemNumber" : "itemNumber",
          "receivedQuantity" : 4,
          "description" : "description",
          "partNumber" : "partNumber"
        },
        "insuredValue" : {
          "amount" : 3.616076749251911,
          "currencySymbol" : "currencySymbol",
          "currency" : "currency"
        },
        "weight" : {
          "units" : "KG",
          "value" : 2.3021358869347655
        },
        "itemDescription" : "itemDescription",
        "dimensions" : {
          "length" : 6,
          "width" : 1,
          "units" : "CM",
          "height" : 5
        },
        "packageSpecialServices" : {
          "signatureOptionDetail" : {
            "signatureOptionType" : "SERVICE_DEFAULT",
            "signatureReleaseNumber" : "signatureReleaseNumber"
          },
          "alcoholDetail" : {
            "alcoholRecipientType" : "LICENSEE",
            "shipperAgreementType" : "shipperAgreementType"
          },
          "dangerousGoodsDetail" : {
            "accessibility" : "ACCESSIBLE",
            "options" : [ "HAZARDOUS_MATERIALS", "HAZARDOUS_MATERIALS" ]
          },
          "pieceCountVerificationBoxCount" : 2,
          "batteryDetails" : [ {
            "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
            "batteryRegulatoryType" : "IATA_SECTION_II",
            "batteryMaterialType" : "LITHIUM_METAL"
          }, {
            "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
            "batteryRegulatoryType" : "IATA_SECTION_II",
            "batteryMaterialType" : "LITHIUM_METAL"
          } ],
          "specialServiceTypes" : [ "ALCOHOL", "ALCOHOL" ],
          "codDetail" : {
            "codCollectionType" : "ANY",
            "codCollectionAmount" : {
              "amount" : 3.616076749251911,
              "currencySymbol" : "currencySymbol",
              "currency" : "currency"
            }
          },
          "dryIceWeight" : {
            "units" : "KG",
            "value" : 2.3021358869347655
          }
        }
      }
    },
    "ReturnShippingTypesInputVO" : {
      "type" : "object",
      "properties" : {
        "shipper" : {
          "$ref" : "#/definitions/Party"
        },
        "recipient" : {
          "$ref" : "#/definitions/Party"
        },
        "serviceType" : {
          "type" : "string",
          "enum" : [ "FIRST_OVERNIGHT", "PRIORITY_OVERNIGHT", "STANDARD_OVERNIGHT", "FEDEX_2_DAY", "FEDEX_2_DAY_AM", "FEDEX_EXPRESS_SAVER", "FEDEX_GROUND", "INTERNATIONAL_GROUND", "FEDEX_HOME_DELIVERY", "FEDEX_FIRST_FREIGHT", "FEDEX_1_DAY_FREIGHT", "FEDEX_2_DAY_FREIGHT", "FEDEX_3_DAY_FREIGHT", "INTERNATIONAL_FIRST", "EUROPE_FIRST_INTERNATIONAL_PRIORITY", "INTERNATIONAL_PRIORITY", "INTERNATIONAL_PRIORITY_EXPRESS", "INTERNATIONAL_PRIORITY_DISTRIBUTION", "INTERNATIONAL_ECONOMY_DISTRIBUTION", "INTERNATIONAL_ECONOMY", "INTERNATIONAL_PRIORITY_FREIGHT", "INTERNATIONAL_ECONOMY_FREIGHT", "SMART_POST", "SMART_POST_MEDIA", "SMART_POST_BOUND_PRINT_MATTER", "FEDEX_FREIGHT_ECONOMY", "FEDEX_FREIGHT_PRIORITY", "SAME_DAY", "SAME_DAY_CITY", "INTERNATIONAL_DISTRIBUTION_FREIGHT", "FEDEX_NEXT_DAY_EARLY_MORNING", "FEDEX_NEXT_DAY_MID_MORNING", "FEDEX_NEXT_DAY_AFTERNOON", "FEDEX_NEXT_DAY_END_OF_DAY", "FEDEX_DISTANCE_DEFERRED", "FEDEX_NEXT_DAY_FREIGHT", "FIRST_OVERNIGHT_EXPRESS_FREIGHT" ]
        },
        "requestedPackageLineItems" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/RequestedPackageLineItem"
          }
        },
        "shipTimestamp" : {
          "type" : "string"
        }
      },
      "example" : {
        "serviceType" : "FIRST_OVERNIGHT",
        "shipper" : {
          "address" : {
            "residential" : false,
            "addressClassification" : "MIXED",
            "city" : "city",
            "countryCode" : "countryCode",
            "streetLines" : [ "streetLines", "streetLines" ],
            "postalCode" : "postalCode",
            "addressVerificationId" : "addressVerificationId",
            "addressClassificationConfidence" : "POTENTIAL",
            "stateOrProvinceCode" : "stateOrProvinceCode",
            "shareId" : "shareId"
          },
          "piece" : {
            "declaredValueCurrencyCode" : "declaredValueCurrencyCode",
            "unitsOfMeasure" : {
              "code" : "code",
              "name" : "name",
              "originalCode" : "originalCode",
              "category" : "category",
              "value" : "value"
            },
            "declaredValue" : 0.80082819046101150206595775671303272247314453125,
            "dimensions" : {
              "length" : 6,
              "width" : 1,
              "units" : "CM",
              "height" : 5
            }
          },
          "contact" : {
            "personName" : "personName",
            "fedralTaxId" : "fedralTaxId",
            "emailAddress" : "emailAddress",
            "parsedPersonName" : {
              "firstName" : "firstName",
              "lastName" : "lastName",
              "middleName" : "middleName",
              "suffix" : "suffix"
            },
            "phoneNumber" : "phoneNumber",
            "contactId" : "contactId",
            "phoneExtension" : "phoneExtension",
            "companyName" : "companyName",
            "faxNumber" : "faxNumber",
            "stateTaxId" : "stateTaxId"
          },
          "accountNumber" : {
            "value" : "value",
            "key" : "key"
          },
          "tins" : [ {
            "number" : "number",
            "tinType" : "BUSINESS_NATIONAL",
            "usage" : "usage",
            "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
            "expirationDate" : "2000-01-23T04:56:07.000+00:00"
          }, {
            "number" : "number",
            "tinType" : "BUSINESS_NATIONAL",
            "usage" : "usage",
            "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
            "expirationDate" : "2000-01-23T04:56:07.000+00:00"
          } ],
          "referenceInfo" : {
            "regulatoryReferenceNumber" : "regulatoryReferenceNumber",
            "yourReference" : "yourReference",
            "countryCode" : "countryCode",
            "postalCode" : "postalCode",
            "purchaseOrderNumber" : "purchaseOrderNumber",
            "departmentNumber" : "departmentNumber",
            "invoiceNumber" : "invoiceNumber",
            "accountNbr" : "accountNbr",
            "shipDate" : "shipDate",
            "referenceValue" : "referenceValue"
          },
          "deliveryInstructions" : "deliveryInstructions",
          "productInfo" : {
            "customsValueAndWeightSpecifiedAsUnit" : false,
            "quantity" : 5,
            "customsValue" : 7.061401241503109105224211816675961017608642578125,
            "weightUnitOfMeasureCode" : "weightUnitOfMeasureCode",
            "description" : "description",
            "weight" : {
              "units" : "KG",
              "value" : 2.3021358869347655
            },
            "sedRequired" : false,
            "productType" : "DOCUMENTS",
            "unitOfMeasureCode" : "unitOfMeasureCode",
            "countryOfManufactureCode" : "countryOfManufactureCode"
          }
        },
        "recipient" : {
          "address" : {
            "residential" : false,
            "addressClassification" : "MIXED",
            "city" : "city",
            "countryCode" : "countryCode",
            "streetLines" : [ "streetLines", "streetLines" ],
            "postalCode" : "postalCode",
            "addressVerificationId" : "addressVerificationId",
            "addressClassificationConfidence" : "POTENTIAL",
            "stateOrProvinceCode" : "stateOrProvinceCode",
            "shareId" : "shareId"
          },
          "piece" : {
            "declaredValueCurrencyCode" : "declaredValueCurrencyCode",
            "unitsOfMeasure" : {
              "code" : "code",
              "name" : "name",
              "originalCode" : "originalCode",
              "category" : "category",
              "value" : "value"
            },
            "declaredValue" : 0.80082819046101150206595775671303272247314453125,
            "dimensions" : {
              "length" : 6,
              "width" : 1,
              "units" : "CM",
              "height" : 5
            }
          },
          "contact" : {
            "personName" : "personName",
            "fedralTaxId" : "fedralTaxId",
            "emailAddress" : "emailAddress",
            "parsedPersonName" : {
              "firstName" : "firstName",
              "lastName" : "lastName",
              "middleName" : "middleName",
              "suffix" : "suffix"
            },
            "phoneNumber" : "phoneNumber",
            "contactId" : "contactId",
            "phoneExtension" : "phoneExtension",
            "companyName" : "companyName",
            "faxNumber" : "faxNumber",
            "stateTaxId" : "stateTaxId"
          },
          "accountNumber" : {
            "value" : "value",
            "key" : "key"
          },
          "tins" : [ {
            "number" : "number",
            "tinType" : "BUSINESS_NATIONAL",
            "usage" : "usage",
            "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
            "expirationDate" : "2000-01-23T04:56:07.000+00:00"
          }, {
            "number" : "number",
            "tinType" : "BUSINESS_NATIONAL",
            "usage" : "usage",
            "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
            "expirationDate" : "2000-01-23T04:56:07.000+00:00"
          } ],
          "referenceInfo" : {
            "regulatoryReferenceNumber" : "regulatoryReferenceNumber",
            "yourReference" : "yourReference",
            "countryCode" : "countryCode",
            "postalCode" : "postalCode",
            "purchaseOrderNumber" : "purchaseOrderNumber",
            "departmentNumber" : "departmentNumber",
            "invoiceNumber" : "invoiceNumber",
            "accountNbr" : "accountNbr",
            "shipDate" : "shipDate",
            "referenceValue" : "referenceValue"
          },
          "deliveryInstructions" : "deliveryInstructions",
          "productInfo" : {
            "customsValueAndWeightSpecifiedAsUnit" : false,
            "quantity" : 5,
            "customsValue" : 7.061401241503109105224211816675961017608642578125,
            "weightUnitOfMeasureCode" : "weightUnitOfMeasureCode",
            "description" : "description",
            "weight" : {
              "units" : "KG",
              "value" : 2.3021358869347655
            },
            "sedRequired" : false,
            "productType" : "DOCUMENTS",
            "unitOfMeasureCode" : "unitOfMeasureCode",
            "countryOfManufactureCode" : "countryOfManufactureCode"
          }
        },
        "shipTimestamp" : "shipTimestamp",
        "requestedPackageLineItems" : [ {
          "physicalPackaging" : "FEDEX_ENVELOPE",
          "groupPackageCount" : 9,
          "itemDescriptionForClearance" : "itemDescriptionForClearance",
          "customerReferences" : [ {
            "customerReferenceType" : "BILL_OF_LADING",
            "value" : "value"
          }, {
            "customerReferenceType" : "BILL_OF_LADING",
            "value" : "value"
          } ],
          "contentRecord" : {
            "itemNumber" : "itemNumber",
            "receivedQuantity" : 4,
            "description" : "description",
            "partNumber" : "partNumber"
          },
          "insuredValue" : {
            "amount" : 3.616076749251911,
            "currencySymbol" : "currencySymbol",
            "currency" : "currency"
          },
          "weight" : {
            "units" : "KG",
            "value" : 2.3021358869347655
          },
          "itemDescription" : "itemDescription",
          "dimensions" : {
            "length" : 6,
            "width" : 1,
            "units" : "CM",
            "height" : 5
          },
          "packageSpecialServices" : {
            "signatureOptionDetail" : {
              "signatureOptionType" : "SERVICE_DEFAULT",
              "signatureReleaseNumber" : "signatureReleaseNumber"
            },
            "alcoholDetail" : {
              "alcoholRecipientType" : "LICENSEE",
              "shipperAgreementType" : "shipperAgreementType"
            },
            "dangerousGoodsDetail" : {
              "accessibility" : "ACCESSIBLE",
              "options" : [ "HAZARDOUS_MATERIALS", "HAZARDOUS_MATERIALS" ]
            },
            "pieceCountVerificationBoxCount" : 2,
            "batteryDetails" : [ {
              "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
              "batteryRegulatoryType" : "IATA_SECTION_II",
              "batteryMaterialType" : "LITHIUM_METAL"
            }, {
              "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
              "batteryRegulatoryType" : "IATA_SECTION_II",
              "batteryMaterialType" : "LITHIUM_METAL"
            } ],
            "specialServiceTypes" : [ "ALCOHOL", "ALCOHOL" ],
            "codDetail" : {
              "codCollectionType" : "ANY",
              "codCollectionAmount" : {
                "amount" : 3.616076749251911,
                "currencySymbol" : "currencySymbol",
                "currency" : "currency"
              }
            },
            "dryIceWeight" : {
              "units" : "KG",
              "value" : 2.3021358869347655
            }
          }
        }, {
          "physicalPackaging" : "FEDEX_ENVELOPE",
          "groupPackageCount" : 9,
          "itemDescriptionForClearance" : "itemDescriptionForClearance",
          "customerReferences" : [ {
            "customerReferenceType" : "BILL_OF_LADING",
            "value" : "value"
          }, {
            "customerReferenceType" : "BILL_OF_LADING",
            "value" : "value"
          } ],
          "contentRecord" : {
            "itemNumber" : "itemNumber",
            "receivedQuantity" : 4,
            "description" : "description",
            "partNumber" : "partNumber"
          },
          "insuredValue" : {
            "amount" : 3.616076749251911,
            "currencySymbol" : "currencySymbol",
            "currency" : "currency"
          },
          "weight" : {
            "units" : "KG",
            "value" : 2.3021358869347655
          },
          "itemDescription" : "itemDescription",
          "dimensions" : {
            "length" : 6,
            "width" : 1,
            "units" : "CM",
            "height" : 5
          },
          "packageSpecialServices" : {
            "signatureOptionDetail" : {
              "signatureOptionType" : "SERVICE_DEFAULT",
              "signatureReleaseNumber" : "signatureReleaseNumber"
            },
            "alcoholDetail" : {
              "alcoholRecipientType" : "LICENSEE",
              "shipperAgreementType" : "shipperAgreementType"
            },
            "dangerousGoodsDetail" : {
              "accessibility" : "ACCESSIBLE",
              "options" : [ "HAZARDOUS_MATERIALS", "HAZARDOUS_MATERIALS" ]
            },
            "pieceCountVerificationBoxCount" : 2,
            "batteryDetails" : [ {
              "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
              "batteryRegulatoryType" : "IATA_SECTION_II",
              "batteryMaterialType" : "LITHIUM_METAL"
            }, {
              "batteryPackingType" : "CONTAINED_IN_EQUIPMENT",
              "batteryRegulatoryType" : "IATA_SECTION_II",
              "batteryMaterialType" : "LITHIUM_METAL"
            } ],
            "specialServiceTypes" : [ "ALCOHOL", "ALCOHOL" ],
            "codDetail" : {
              "codCollectionType" : "ANY",
              "codCollectionAmount" : {
                "amount" : 3.616076749251911,
                "currencySymbol" : "currencySymbol",
                "currency" : "currency"
              }
            },
            "dryIceWeight" : {
              "units" : "KG",
              "value" : 2.3021358869347655
            }
          }
        } ]
      }
    },
    "ReturnShippingTypesOutputVO" : {
      "type" : "object",
      "properties" : {
        "returnTypes" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "FEDEX_TAG", "NET_RETURN", "PENDING", "PRINT_RETURN_LABEL", "EMAIL_LABEL", "VOICE_CALL_TAG" ]
          }
        },
        "cxsalerts" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/CXSAlert"
          }
        }
      },
      "example" : {
        "returnTypes" : [ "FEDEX_TAG", "FEDEX_TAG" ],
        "cxsalerts" : [ {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        }, {
          "code" : "code",
          "alertType" : "NOTE",
          "message" : "message"
        } ]
      }
    },
    "SignatureOptionDetail" : {
      "type" : "object",
      "properties" : {
        "signatureOptionType" : {
          "type" : "string",
          "enum" : [ "SERVICE_DEFAULT", "NO_SIGNATURE_REQUIRED", "INDIRECT", "DIRECT", "ADULT" ]
        },
        "signatureReleaseNumber" : {
          "type" : "string"
        }
      },
      "example" : {
        "signatureOptionType" : "SERVICE_DEFAULT",
        "signatureReleaseNumber" : "signatureReleaseNumber"
      }
    },
    "TaxpayerIdentification" : {
      "type" : "object",
      "properties" : {
        "tinType" : {
          "type" : "string",
          "enum" : [ "BUSINESS_NATIONAL", "BUSINESS_STATE", "BUSINESS_UNION", "PERSONAL_NATIONAL", "PERSONAL_STATE", "FEDERAL" ]
        },
        "number" : {
          "type" : "string"
        },
        "usage" : {
          "type" : "string"
        },
        "effectiveDate" : {
          "type" : "string",
          "format" : "date-time"
        },
        "expirationDate" : {
          "type" : "string",
          "format" : "date-time"
        }
      },
      "example" : {
        "number" : "number",
        "tinType" : "BUSINESS_NATIONAL",
        "usage" : "usage",
        "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
        "expirationDate" : "2000-01-23T04:56:07.000+00:00"
      }
    },
    "UnitsOfMeasure" : {
      "type" : "object",
      "properties" : {
        "category" : {
          "type" : "string"
        },
        "code" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string"
        },
        "value" : {
          "type" : "string"
        },
        "originalCode" : {
          "type" : "string"
        }
      },
      "example" : {
        "code" : "code",
        "name" : "name",
        "originalCode" : "originalCode",
        "category" : "category",
        "value" : "value"
      }
    },
    "Weight" : {
      "type" : "object",
      "properties" : {
        "units" : {
          "type" : "string",
          "enum" : [ "KG", "LB" ]
        },
        "value" : {
          "type" : "number",
          "format" : "double"
        }
      },
      "example" : {
        "units" : "KG",
        "value" : 2.3021358869347655
      }
    }
  }
}